test

diff --git a/.github/workflows/Temp-workflow.yml b/.github/workflows/Temp-workflow.yml
--- a/.github/workflows/Temp-workflow.yml
+++ b/.github/workflows/Temp-workflow.yml
@@ -45,8 +45,8 @@ jobs:
           name: ada-test-report
           path: reports
           run: |
-          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
-          exit 1
+            echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
+            exit 1
   deploy:
     needs: accessibility
     runs-on: ubuntu-latest
