test

diff --git a/.github/workflows/Temp-workflow.yml b/.github/workflows/Temp-workflow.yml
--- a/.github/workflows/Temp-workflow.yml
+++ b/.github/workflows/Temp-workflow.yml
@@ -38,12 +38,17 @@ jobs:
         run: npx wait-on http://127.0.0.1:4000 &
       - name: Test Accessibility
         id: run-ada-tests
-        run: npm run accessibility
-      - name: Upload test report
-        uses: actions/upload-artifact@v3
+        run: npm run accessibility 2>&1 | tee pa11y_output.txt
+      - name: Read pa11y_output file.
+        id: pa11y_output
+        uses: juliangruber/read-file-action@v1
         with:
-          name: ada-test-report
-          path: ada-test.json
+          path: ./pa11y_output.txt
+      - name: Check for pa11y failures.
+        if: contains(steps.pa11y_output.outputs.content, 'errno 2')
+        run: |
+          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
+          exit 1
   deploy:
     needs: accessibility
     runs-on: ubuntu-latest
