test

diff --git a/.github/workflows/Temp-workflow.yml b/.github/workflows/Temp-workflow.yml
--- a/.github/workflows/Temp-workflow.yml
+++ b/.github/workflows/Temp-workflow.yml
@@ -25,7 +25,7 @@ jobs:
       - name: Install dependencies
         if: steps.cache.outputs.cache-hit != 'true'
         run: npm install
-      - name: Setup Chrome
+      - name: Setup Chrome Browser
         uses: browser-actions/setup-chrome@v1
         with:
           chrome-version: beta
@@ -38,17 +38,15 @@ jobs:
         run: |
           sleep 10
           npm run accessibility-test
-      - name: Check for pa11y failures
-        if: failure() && steps.run-ada-tests.outcome == 'failure'
-        run: |
-          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
-          exit 1
-      - name: Upload test report
+      - name: Accessbility test status
         if: failure() && steps.run-ada-tests.outcome == 'failure'
         uses: actions/upload-artifact@v3
         with:
           name: ada-test-report
-          path: ada-test.json
+          path: reports
+          run: |
+          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
+          exit 1
   deploy:
     needs: accessibility
     runs-on: ubuntu-latest
